import { useState } from "react";
import {
  Alert,
  AlertDescription,
  AlertIcon,
  Box,
  Button,
  FormControl,
  FormHelperText,
  FormLabel,
  HStack,
  Input,
  Select,
  Stack,
  Text,
  Textarea,
} from "@chakra-ui/react";

import type { CopySuggestion, ImageStyleOptions } from "../types";

const aspectRatioOptions = [
  { label: "1:1 Square", value: "1:1" },
  { label: "4:5 Portrait", value: "4:5" },
  { label: "16:9 Widescreen", value: "16:9" },
];

const parsePalette = (value: string): string[] | undefined => {
  const entries = value
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean);

  return entries.length > 0 ? entries : undefined;
};

interface ImageConfirmationStepProps {
  selectedCopy: CopySuggestion | null;
  onGenerate: (style: ImageStyleOptions) => void;
  providerName?: string;
  isDisabled?: boolean;
  isLoading?: boolean;
  error?: string | null;
}

export const ImageConfirmationStep = ({
  selectedCopy,
  onGenerate,
  providerName,
  isDisabled = false,
  isLoading = false,
  error,
}: ImageConfirmationStepProps) => {
  const [palette, setPalette] = useState("soft lilac, dawn peach");
  const [medium, setMedium] = useState("Film photography");
  const [mood, setMood] = useState("Dreamy optimism");
  const [aspectRatio, setAspectRatio] = useState("4:5");

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!selectedCopy) {
      return;
    }

    const style: ImageStyleOptions = {};

    if (palette.trim()) {
      const parsedPalette = parsePalette(palette);
      if (parsedPalette) {
        style.palette = parsedPalette;
      }
    }

    if (medium.trim()) {
      style.medium = medium.trim();
    }

    if (mood.trim()) {
      style.mood = mood.trim();
    }

    if (aspectRatio) {
      style.aspectRatio = aspectRatio;
    }

    onGenerate(style);
  };

  return (
    <Box as="form" onSubmit={handleSubmit}>
      <Stack spacing={4}>
        <Stack spacing={1}>
          <Text fontWeight="semibold">Confirm copy direction</Text>
          <Text fontSize="sm" color="subtle">
            {selectedCopy
              ? "Fine-tune visual style before generating the image."
              : "Select a copy variant to continue."}
          </Text>
        </Stack>

        <Textarea
          value={selectedCopy?.text ?? ""}
          isReadOnly
          placeholder="Selected copy will appear here"
          rows={4}
        />

        <Stack spacing={4}>
          <FormControl>
            <FormLabel>Palette</FormLabel>
            <Input
              value={palette}
              onChange={(event) => setPalette(event.target.value)}
              placeholder="comma-separated colors"
            />
            <FormHelperText>Helps nudge the visual mood (max 8 colours).</FormHelperText>
          </FormControl>

          <HStack spacing={4} align="flex-start" flexWrap="wrap">
            <FormControl flex="1" minW={{ base: "100%", md: "220px" }}>
              <FormLabel>Medium</FormLabel>
              <Input
                value={medium}
                onChange={(event) => setMedium(event.target.value)}
                placeholder="e.g. Soft illustration"
              />
            </FormControl>

            <FormControl flex="1" minW={{ base: "100%", md: "220px" }}>
              <FormLabel>Mood</FormLabel>
              <Input
                value={mood}
                onChange={(event) => setMood(event.target.value)}
                placeholder="e.g. Cozy minimalism"
              />
            </FormControl>

            <FormControl flex="1" minW={{ base: "100%", md: "220px" }}>
              <FormLabel>Aspect ratio</FormLabel>
              <Select value={aspectRatio} onChange={(event) => setAspectRatio(event.target.value)}>
                {aspectRatioOptions.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </Select>
            </FormControl>
          </HStack>
        </Stack>

        {error ? (
          <Alert status="error" borderRadius="lg">
            <AlertIcon />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        ) : null}

        <HStack justify="space-between" align="center">
          <Text fontSize="sm" color="subtle">
            {providerName ? `Images will be generated by ${providerName}` : "Image provider active"}
          </Text>
          <Button
            type="submit"
            variant="primary"
            isDisabled={isDisabled || !selectedCopy}
            isLoading={isLoading}
          >
            Generate image
          </Button>
        </HStack>
      </Stack>
    </Box>
  );
};
